<a href="https://colab.research.google.com/github/MehrdadMatin/Generative-AI/blob/main/Text_Representation_Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bag of Words

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.DataFrame({'text':['people watch actors',
                           'actors watch actors',
                           'people write reviews',
                           'actors write reviews'], 'output':[1,1,0,0]})

df

text  output
0   people watch actors       1
1   actors watch actors       1
2  people write reviews       0
3  actors write reviews       0

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [14]:
bow = cv.fit_transform(df['text'])

In [15]:
#vocabulary
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'actors': 0, 'write': 4, 'reviews': 2}


In [16]:
bow.toarray()

array([[1, 1, 0, 1, 0],
       [2, 0, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1]])

In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 1 0 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]


In [22]:
#new
cv.transform(["people watch movies"]).toarray()

array([[0, 1, 0, 1, 0]])

In [23]:
x = bow.toarray()
y = df['output']

#N-grams

In [24]:
df = pd.DataFrame({'text':['people watch actors',
                           'actors watch actors',
                           'people write reviews',
                           'actors write reviews'], 'output':[1,1,0,0]})

df

text  output
0   people watch actors       1
1   actors watch actors       1
2  people write reviews       0
3  actors write reviews       0

In [25]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [26]:
bow = cv.fit_transform(df['text'])

In [27]:
print(cv.vocabulary_)

{'people watch': 2, 'watch actors': 4, 'actors watch': 0, 'people write': 3, 'write reviews': 5, 'actors write': 1}


In [28]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [38]:
#Ti gram
# BI gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [39]:
bow = cv.fit_transform(df['text'])

In [40]:
print(cv.vocabulary_)

{'people watch actors': 2, 'actors watch actors': 0, 'people write reviews': 3, 'actors write reviews': 1}


In [41]:
bow.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

#TF-IDF (Term frequency - Inverse document frequency)

In [42]:
df = pd.DataFrame({'text':['people watch actors',
                           'actors watch actors',
                           'people write reviews',
                           'actors write reviews'], 'output':[1,1,0,0]})

df

text  output
0   people watch actors       1
1   actors watch actors       1
2  people write reviews       0
3  actors write reviews       0

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [45]:
arr = tfid.fit_transform(df['text']).toarray()

In [46]:
arr

array([[0.49681612, 0.61366674, 0.        , 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.        , 0.61366674, 0.        , 0.61366674]])

In [47]:
print(tfid.idf_)
print(tfid.vocabulary_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
{'people': 1, 'watch': 3, 'actors': 0, 'write': 4, 'reviews': 2}
